apiVersion: v1
kind: Service
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: service-2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  namespace: default
  labels:
    app: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: service-2
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            tcpSocket:
              port: 8080