server:
  port: 8080
spring:
  application:
    name: service-1
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://www.smarteye.health/auth/realms/dev-realm

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
  org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"