server:
  port: 8080
spring:
  application:
    name: service-1
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.96.49.151:7000/auth/realms/demo-realm

management:
  endpoints:
    web:
      exposure:
        include: "*"