server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      routes:
        - id: route-1
          uri: http://service-1:8080/
          predicates:
            - Path=/service-1/**
        - id: route-2
          uri: http://service-2:8080/
          predicates:
            - Path=/service-2/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://www.smarteye.health/auth/realms/dev-realm
      client:
        provider:
          keycloak:
            token-uri: https://www.smarteye.health/auth/realms/dev-realm/protocol/openid-connect/token
            authorization-uri: https://www.smarteye.health/auth/realms/dev-realm/protocol/openid-connect/auth
            userinfo-uri: https://www.smarteye.health/auth/realms/dev-realm/protocol/openid-connect/userinfo
            jwk-set-uri: https://www.smarteye.health/auth/realms/dev-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          springcloud-scope:
            provider: keycloak
            client-id: smarteye-service
            client-secret: 58b58181-fe6d-4582-b8f5-451cf9fe616c
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
  org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"




